graasp/client

.github/workflows/ci.yml
.github/workflows/deploy-stage.yml
README.md
package.json
src/components/App.tsx
src/components/Root.tsx
src/components/common/UserSwitchWrapper.tsx
src/config/constants.ts
src/config/i18n.ts
src/env.json
vite.config.ts
yarn.lock

- fix: update deps
- fix: update readme
- fix #25

fix: update deps and env var

---

src/components/App.tsx
src/components/Root.tsx
src/components/main/DeleteMemberDialog.tsx
src/langs/en.json
src/langs/fr.json

In this PR:
- add a redirection to auth when not logged in
- add a text for the cancel "delete account" button

fix: update message and redirect to auth

---

src/components/Root.tsx
src/components/common/TextField.tsx
src/components/main/StatusBar.tsx
src/config/notifier.ts
src/langs/en.json

In this PR:
- fix #57
- fix start adornment in social links is a button but does nothing

fix: add translations for notifier profile update and creation

---

package.json
src/components/layout/Header.tsx
yarn.lock

fix: fix platform mobile colors

---

cypress/e2e/profile.cy.ts
cypress/fixtures/members.ts
cypress/support/commands.ts
cypress/support/server.ts
cypress/tsconfig.json
package.json
src/components/main/EditingNameField.tsx
src/components/main/UsernameForm.tsx
src/config/selectors.ts
src/langs/ar.json
src/langs/de.json
src/langs/en.json
src/langs/es.json
src/langs/fr.json
src/langs/it.json
src/pages/MemberScreen.tsx
tsconfig.json
yarn.lock

#29 
https://github.com/graasp/graasp-account/assets/58473159/f0705585-52c4-449d-b411-af3be804e07c

feat: allow to change username

---

cypress/fixtures/members.ts
package.json
src/components/main/EditingNameField.tsx
yarn.lock

In this PR I apply the new limits from sdk for the username length

fix: apply new limits

---

src/pages/MemberScreen.tsx

feat: delete delete account from main profile page

---

cypress/e2e/profile.cy.ts
cypress/support/commands.ts
cypress/support/server.ts
src/components/main/LanguageSwitch.tsx
src/pages/MemberScreen.tsx

fix(test): ensure language can be changed with the select

---

src/App.tsx
src/components/main/DeleteMemberSection.tsx
src/components/main/MainMenu.tsx
src/langs/ar.json
src/langs/de.json
src/langs/en.json
src/langs/es.json
src/langs/fr.json
src/langs/it.json
src/pages/SettingsScreen.tsx

feat: rename Destructive settings to Settings

---

.gitignore
.vscode/settings.json
src/components/main/DeleteMemberDialogContent.tsx
src/components/main/DeleteMemberSection.tsx

fix: issue on delete-account-button

---

.eslintrc
.eslintrc.json
.prettierrc
cypress/cypress.d.ts
cypress/e2e/homePage.cy.ts
cypress/e2e/storage.cy.ts
cypress/support/commands.ts
cypress/support/server.ts
cypress/tsconfig.json
src/config/selectors.ts
src/pages/StorageScreen.tsx

In this PR:
- add a small test to check the storage interface
- add type annotations to the `setUpApi` command
- remove unused intercepts

fix: add storage intercept and test

---

cypress/e2e/settings/exportData.cy.ts
cypress/support/commands.ts
cypress/support/server.ts
package.json
src/config/notifier.ts
src/config/selectors.ts
src/langs/en.json
src/langs/fr.json
src/modules/settings/ExportData.tsx
src/pages/SettingsScreen.tsx
yarn.lock

#318 
[exportData.webm](https://github.com/user-attachments/assets/85842fba-fd63-4308-ba63-81fcbf70864f)

feat: add data export button in settings page

---

package.json
src/Root.tsx
yarn.lock

feat: arabic view - rtl

---

cypress/e2e/notFoundPage.cy.ts
src/App.tsx
src/config/selectors.ts
src/langs/en.json
src/langs/fr.json
src/pages/HomePage.tsx
src/pages/NotFoundPage.tsx
src/pages/PageWrapper.tsx

feat: add 404 page

---

cypress/e2e/settings/deleteMember.cy.ts
cypress/support/commands.ts
cypress/support/server.ts
src/components/main/DeleteMemberDialogContent.tsx
src/components/main/DeleteMemberSection.tsx
src/config/selectors.ts

In this PR:
- add tests for delete member feature
- remove deprecated delete member hook usage and replace by deleteCurrentMember hook

fix: add tests for delete member feature

---

cypress/e2e/profile/personalInformation.cy.ts
src/langs/de.json
src/langs/en.json
src/langs/es.json
src/langs/fr.json
src/langs/it.json
src/modules/profile/EditPersonalInformation.tsx

Relates to https://github.com/graasp/graasp/pull/1406

fix: do not allow special characters in username

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-stage.yml

In this PR:
- update deployment to use proper installation steps

fix: update deployments to use propper install steps

---

.gitignore
.prettierrc
tsconfig.app.json
vite.config.ts

This PR is stacked on top of #429
- **fix: add alias for modules import**

fix: add alias for modules import

---

vite.config.ts

feat: add backend proxy

---

package.json
public/locales/en/landing.json
src/modules/landing/footer/Footer.tsx
src/modules/landing/home/UserStory.tsx
src/modules/landing/home/UserStorySection.tsx

fix: landing page with small adjustments

---

.github/workflows/test.yml
cypress/e2e/player/autoLogin.cy.ts
cypress/e2e/player/redirections.cy.ts
package.json
pnpm-lock.yaml
public/locales/it/auth.json
src/AuthContext.tsx
src/components/langs.ts
src/config/i18n.ts
src/main.tsx
src/modules/auth/components/Footer.tsx
src/modules/auth/components/Redirection.tsx
src/modules/player/item/ItemForbiddenScreen.tsx
src/routes/player/$rootId/$itemId/autoLogin.tsx

In this PR:
- add language detector and store the language in localStorage
- add unit tests in CI

feat: add language detector

---

cypress/fixtures/fileLinks.ts

fix: add https to fixture url

---

cypress/e2e/auth/logInWithPassword.cy.ts
cypress/support/commands.ts
cypress/support/server.ts
src/locales/fr/landing.json
src/modules/landing/features/CallOutSection.tsx
src/modules/landing/features/pricing/IncludedOption.tsx
src/modules/landing/features/pricing/PlanLayout.tsx
src/modules/landing/features/pricing/PricingPlansSection.tsx

chore: code smells

---

cypress/e2e/builder/item/edit/editFile.cy.ts

chore(ci): skip flaky test

---

.github/workflows/deploy-storybook.yml
cypress/e2e/account/homePage.cy.ts
cypress/fixtures/items.ts
src/locales/en/builder.json
src/modules/builder/components/item/ItemContent.tsx
src/modules/player/common/ItemCard.tsx
src/routes/builder/items/$itemId/index.tsx

fix: shortcut and storybook build

---

src/locales/en/builder.json
src/modules/builder/components/input/DebouncedTextEditor.tsx
src/modules/builder/components/item/edit/EditModal.tsx
src/modules/builder/components/item/form/BaseItemForm.tsx
src/modules/builder/components/item/form/description/DescriptionAndPlacementForm.tsx
src/modules/builder/components/item/form/description/DescriptionForm.tsx
src/modules/builder/components/item/form/document/DocumentContentForm.tsx
src/modules/builder/components/item/form/file/FileForm.tsx
src/modules/builder/components/item/form/link/LinkDescriptionField.tsx
src/modules/builder/components/item/form/link/LinkEditForm.tsx
src/modules/builder/components/item/form/link/LinkForm.tsx
src/modules/builder/components/item/publish/EditItemDescription.tsx
src/ui/TextEditor/TextEditor.stories.tsx
src/ui/TextEditor/TextEditor.tsx

Fix the description of links when editing item.
I downgraded the description to a simple multiline text area.
ref #618

fix: link description

---

cypress/e2e/account/homePage.cy.ts
src/locales/ar/account.json
src/locales/de/account.json
src/locales/en/account.json
src/locales/es/account.json
src/locales/fr/account.json
src/locales/it/account.json
src/modules/account/home/MemberCard.tsx
src/modules/home/MenuTabs.tsx
src/routes/_memberOnly/account/settings.tsx
src/routes/_memberOnly/home.tsx

feat: move member welcome card in settings

---

src/modules/home/MenuTabs.tsx
src/ui/MenuTab/MenuTab.stories.tsx
src/ui/MenuTab/MenuTab.tsx

fix: refactor menuTabs to use tsr link

---

src/locales/en/home.json
src/modules/home/bookmarks/BookmarkCard.tsx
src/modules/home/bookmarks/BookmarkedItems.tsx
src/modules/home/bookmarks/ItemFavoriteCard.tsx

fix: add limit on bookmarks shown

---

src/components/ui/CardActionAreaLink.tsx
src/modules/home/bookmarks/BookmarkCard.tsx

close #921 
Add umami event when clicking bookmark card

fix: add umami data on bookmark card

---

cypress/e2e/builder/item/create/createDocument.cy.ts
src/modules/builder/components/item/form/document/DocumentCreateForm.tsx

fix: update validation for text on description change

---

src/config/notifier.ts
src/modules/auth/components/common/ErrorDisplay.tsx
src/query/item/create/mutations.ts
src/query/mutations/membership.test.ts
src/query/mutations/membership.ts
src/query/types.ts

fix: notifications and login errors

---

cypress/e2e/builder/item/create/createApp.cy.ts
cypress/e2e/builder/item/create/createDocument.cy.ts
cypress/e2e/builder/item/create/createLink.cy.ts
cypress/e2e/builder/item/create/importH5p.cy.ts
cypress/e2e/builder/item/create/importZip.cy.ts
cypress/e2e/builder/item/home/home.cy.ts
cypress/e2e/home/home.cy.ts
src/modules/builder/components/item/FolderContent.tsx
src/modules/builder/components/pages/home/HomeScreenContent.tsx
src/routes/_memberOnly/_homeLayout/home.tsx

drop zone inside a folder: (home page only has new folder)
home page:

feat: remove add new item on home page

---

src/locales/en/builder.json
src/locales/fr/builder.json
src/modules/builder/components/file/FileUploader.tsx
src/ui/upload/FileDropper/FileDropper.tsx

feat: add tutorial links in dropzone

---

cypress/e2e/builder/item/create/createLink.cy.ts
cypress/e2e/builder/item/edit/editLink.cy.ts
src/modules/builder/components/item/form/link/LinkEditForm.tsx
src/modules/builder/components/item/form/link/LinkForm.tsx
src/modules/builder/components/item/form/link/LinkLayout.tsx
src/modules/builder/components/item/form/link/LinkTypeFormControl.tsx
src/modules/builder/components/item/form/link/LinkUrlField.tsx
src/ui/items/withCaption.tsx

- Create a `LinkTypeFormControl` component, reused by edit and create forms
- use generation's edit and create endpoint for links: invalidation happens in the form as well
WAIT FOR HOME PAGE UPDATE BEFORE MERGE
close #931

feat: allow to edit link url

---

.github/workflows/test.yml
src/config/notifier.ts
src/locales/en/account.json
src/modules/account/settings/publicProfile/PublicProfile.tsx

fix: show inline notifications for public profile

---

README.md

In this PR I update the documentation to running the client.

fix: update documentation on how to run the app

---

package.json
pnpm-lock.yaml
src/modules/builder/components/input/MultiSelectTagChipInput.tsx
src/modules/builder/components/item/publish/customizedTags/CustomizedTags.tsx
src/modules/builder/components/item/publish/customizedTags/useTagsManager.tsx
src/query/api/search.ts
src/query/keys.ts
src/query/tag/api.ts
src/query/tag/hooks.ts
src/query/tag/keys.ts
src/query/tag/routes.ts

In this PR I update the code with the changes made in SDK. Mainly concerned is the `TagCategory` that was moved from an enum to a const.

fix: update for new sdk version

---

src/locales/en/landing.json
src/modules/landing/aboutUs/ContactSection.tsx
src/modules/landing/footer/Footer.tsx
src/routes/_landing/about-us.tsx
src/routes/_landing/contact-us.tsx

In this PR I complte the contact page with emails and social links.
UPDATED:
Old version:

feat: complete contact page

---

.github/workflows/deploy-storybook.yml
.github/workflows/test.yml

Upgrade pnpm version used in the storybook workflow to use latest (`10`)

fix: pnpm version in storybook deploy workflow

---

.storybook/main.ts
package.json
pnpm-lock.yaml
src/modules/landing/Platforms/PlatformCube.mdx
src/modules/landing/header/RightHeader.mdx
src/ui/Main/LogoHeader.mdx

fix: add missing storybook/addon-docs for MDX content

---

package.json
pnpm-lock.yaml
src/components/page/Editor.tsx
src/components/page/StatusToolbar.tsx
src/components/page/useYjs.ts
src/modules/builder/components/item/ItemContent.tsx

Setup yjs for collaboration.
Shows current active users.
Do not save content (some content may be persisted because of the server state).
https://github.com/user-attachments/assets/79ae3ab7-d52a-4bfc-b178-7d10077253bc

feat: setup collaboration with yjs for pages

---

src/modules/builder/components/item/header/ModeButton.tsx

Define if the layout is an important feature by tracking it with umami.
ref https://github.com/graasp/client/issues/1065

refactor: send umami event on layout change

---

cypress/support/server.ts
src/components/ui/HeaderRightContent.tsx
src/locales/en/messages.json
src/modules/account/settings/preferences/EditPreferences.tsx
src/modules/account/settings/profile/EditPersonalInformation.tsx
src/query/member/api.ts
src/query/member/mutations.test.ts
src/query/member/mutations.ts
src/query/member/routes.ts
src/query/member/routines.ts
src/routes/_landing.tsx

Use generation for PATCH `members/current`
At some point settings can be refactored with react hook form.

refactor: use generation to edit current member

---

src/components/page/plugins/FontDropDown.tsx
src/components/page/plugins/ToolbarPlugin.tsx

feat: add page font family dropdown

---

.github/workflows/test.yml
src/ui/items/appItemHooks.ts

fix: add catch for message parsing errors from apps

---

src/modules/builder/components/item/form/folder/FolderCreateForm.tsx

Allow creating pages only inside folder.
TODO: change docs

feat: allow creating pages only inside folders

---

cypress/e2e/home/home.cy.ts
cypress/support/commands.ts
src/AuthContext.tsx
src/config/localStorage.ts
src/modules/home/useLocalStorage.tsx
src/modules/landing/preview/PreviewModeContext.tsx

fix: catch local storage errors
