graasp/client

src/components/main/MainMenu.tsx
src/components/main/StockageScreen.tsx
src/langs/de.json
src/langs/en.json
src/langs/fr.json

In this PR I fix an inconsistancy in the translations for the storage list item. It said "Stockage" when it should be "Storage"
fix #47

fix(trans): storage translations

---

.github/workflows/cypress.yml
cypress.config.ts
cypress/cypress.d.ts
cypress/e2e/profile.cy.ts
cypress/fixtures/members.ts
cypress/support/commands.ts
cypress/support/e2e.ts
cypress/support/server.ts
cypress/support/utils.ts

test: add cypress

---

src/pages/PublicProfileScreen.tsx

fix: accept query params for validation social links

---

src/components/main/AvatarUploader.tsx
src/components/main/MemberCard.tsx
src/config/constants.ts

fix: fix avatar size constant

---

cypress/fixtures/members.ts
src/components/main/CropModal.tsx
src/components/main/MemberCard.tsx

In this PR I fix an issue where the user avatar picture was artificially growing in size before being sent to the backend. This resulted in a silent error and failure to update the avatar picture. With this PR I update the code that handles cropping and creating a new image. It uses lossy compression to reduce the file size and ensure we do not hit the limit of 10Mb that we fixed for file uploads.
Maybe this component should be moved to UI alongside a custom hook to compute the image crop. @ReidyT were you working on that recently ?

fix: avatar upload size error

---

docs/storage/uploaded-file-list-specification.md

this PR is to rename `currentPage` in Pagination to `page` so that it aligns with what already exists in the code, and delete `totalPages` attribute because having both `totalItems` and `totalPages` along with `pageSize` can be redundant

fix: rename pagination attributes in uploaded files spec

---

src/components/main/MemberStorageFiles.tsx

Since the max page size is set to 50 in the backend so I deleted the select of 100 items

fix: remove page size option that exceeds the maximum allowed in storage table

---

.eslintrc.json
.vscode/settings.json
cypress/e2e/homePage.cy.ts
cypress/e2e/notFoundPage.cy.ts
cypress/e2e/profile/password.cy.ts
cypress/e2e/profile/personalInformation.cy.ts
cypress/e2e/profile/publicProfile.cy.ts
cypress/e2e/settings/deleteMember.cy.ts
cypress/e2e/settings/exportData.cy.ts
cypress/e2e/settings/preferences.cy.ts
cypress/e2e/storage.cy.ts
cypress/e2e/validateEmailPage.cy.ts
cypress/tsconfig.json
package.json
src/modules/settings/ExportData.tsx
tsconfig.app.json
tsconfig.json
tsconfig.node.json

In this PR: 
- update ts config
- remove paths in tests as they do not work well with Cypress see #378

fix: update ts config

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-stage.yml
README.md
umami.plugin.ts
vite.config.ts

In this PR I add a custom vite plugin that inserts the umami script tag into the html output file if the `UMAMI_WEBSITE_ID` env variable is set. 
This removes the error that the builder has when the variable is not set. It was also a nice experience to see how it is possible to manipulate the outputted HTML code in vite !

feat: add umami plugin in vite config

---

.github/workflows/ci.yml

In this PR:
- use the specified node version from `package.json` for setting up node in the CI.
close #385

fix: use package.json defined node version in ci

---

cypress/e2e/settings/preferences.cy.ts
src/components/main/EditMemberPreferences.tsx

In this PR: show the right language in the switch when editing the member language.
Previously it was staying on the current language.
It now changes to show the selected language when the select closes.

fix: updated lang is not shown in preferences when switching lang

---

src/modules/account/settings/password/CreatePassword.tsx
src/modules/account/settings/password/EditPassword.tsx
src/modules/auth/components/requestPasswordReset/RequestPasswordReset.tsx
src/modules/auth/components/requestPasswordReset/ResetPassword.tsx
src/modules/auth/components/signIn/MagicLinkLoginForm.tsx
src/modules/auth/components/signIn/PasswordLoginForm.tsx
src/modules/auth/validation.ts
src/routes/auth/reset-password.tsx

In this PR:
- use a translated string for the value of the `required` option in react hook form and remove the need for translating the error after the fact

fix: use translation for required validation

---

cypress/e2e/player/island.cy.ts
src/config/selectors.ts
src/modules/landing/footer/CopyrightText.stories.tsx
src/modules/landing/footer/CopyrightText.tsx
src/modules/landing/footer/Footer.tsx
src/modules/landing/preview/PreviewModeContext.tsx
src/modules/player/navigationIsland/NavigationIsland.tsx
src/routes/__root.tsx
src/routes/_landing.tsx
src/routes/_landing/features.tsx

In this PR:
- fix #532 
https://github.com/user-attachments/assets/54782209-0786-435c-8d64-e7ba6cce45e5
When you triple click on the copy right text it enables the "Preview" mode. The graasp logo show that you are in "Preview Mode, the copy right text as well. 
It adds a localStorage item.
It shows components guarded by `Preview` wrappers. This allows to push changes but not make them available to customers directly. 
Currently only a single key is used and its presence is used to show or hide content.
We could extend this feature to specific feature sets, like `landing`, `ui` etc ... that would allow to selectively have control over the preview features you want to enable.

feat: add preview mode

---

src/routeTree.gen.ts
src/routes/auth/signin.tsx
src/routes/signin.tsx

In this PR I add 2 legacy supporting routes that support the usage of `/signin` and `/auth/signin` that is used by e.g. builder. They both redirect to the new `/auth/login` route. 
I have specified that these routes should be deleted in 6months.

fix: add redirection page for login from legacy services

---

src/modules/analytics/PageWrapper.tsx
src/routeTree.gen.ts
src/routes/analytics/index.tsx
src/routes/analytics/items/$itemId.tsx

In this PR I add the platform switch back to analytics to allow switching to the player or builder view.
The analytics and library icons are disabled.

fix: platform switch in analytics

---

.github/workflows/test.yml
src/config/env.ts
vite.config.ts

In this PR I make the H5P integration env var required when we make a production build.
I also update the url of the h5p integration provided by the backend when we are in dev as it is easier than having to deploy a separate h5p bucket with the integration.
The route had changed. There will be a PR in the backend to update it.
Below is an example of the error message that is displayed when the var is missing:
It is possible to require any env var by name in the build process by calling `requireEnvVariable("MYVAR")`.

fix: h5p integration and require h5p env var in prod build

---

src/modules/account/PageWrapper.tsx

In this PR I make a small fix to disable the navigation to `/player` and `/analytics` from the home of account since the bare pages are not very usefull in this context.
For example the player page just redirects back to /account ... so there is not a lot of use.

fix: disable navigation to player and analytics home from account

---

src/components/ui/MainMenuItem.tsx
src/modules/builder/components/main/MainMenu.tsx
src/routes/builder/_layout.tsx
src/routes/builder/items/$itemId.tsx
src/ui/Main/Main.tsx
src/ui/MainMenu/MenuItem/MenuItem.tsx
src/ui/PlatformSwitch/PlatformSwitch.tsx

I have the impression that sending umami events on page navigation causes full-page reloads. This is not intended.
I think we should stick to sending "events" when user interact with buttons in the interface that have JS actions, for navigation related events we should either use the explicit umami.track method or rely simply on navigation tracking (the dashboard shows which pages were accessed).
I am open to discussions and maybe we need to investigate this a bit more.

fix: umami event on navigation cause full-page reload

---

src/components/ui/Navigator/CurrentItemNavigation.tsx
src/components/ui/Navigator/ParentsNavigation.tsx
src/modules/analytics/Navigator.tsx

In this PR I fix a silly bug related to the navigator in analytics.
The children arrow was incorrectly aligned below the element name when it should be in the same row.
I also removed the laoding states to decrease the flickering when navigating between items.

fix: analytics navigator arrow is miss-aligned

---

src/AuthContext.tsx
src/modules/builder/components/item/copy/CopyModal.tsx
src/modules/builder/components/item/move/MoveModal.tsx
src/modules/builder/components/item/sharing/csvImport/TemplateSelectionButton.tsx
src/modules/builder/components/item/shortcut/CreateShortcutModal.tsx
src/modules/builder/components/main/itemSelectionModal/ItemSelectionModal.tsx

Fixing some modal titles that were left broken during the builder integration.
I moved the translation on the calling side to make it better on the type-checking of the translations.

fix: modal titles

---

cypress/e2e/player/navigation.cy.ts
src/config/selectors.ts
src/modules/player/navigationIsland/PreviousNextButtons.tsx
src/modules/player/navigationIsland/customButtons.tsx

In this PR I fix an issue with the navigation island in the player.
The value for the next button was always `null` because on a mistake on the boundary check (classic...).
So the buttons were not shown on the root, because both of them were null.
Inside the children, the next button did nothing. It was "disabled" but the styles were not applied correctly since we migrated from a `button` tag on an anchor `a` tag. Achors can not really be disabled in the semantical sens, instead tanstack router simply removes the href attribute. 
So we had to change the styles from `:disabled` (pseudo element disabled) to `[disabled]` (attribute disabled is present).
Also added a test to check that it works.
Thank you @pyphilia for noticing !
closes #797

fix: navigation buttons issues

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-stage.yml
.github/workflows/deploy-storybook.yml
.github/workflows/test.yml
src/lib/ClientManager.ts
vite.config.ts

Share page crashes if there are shortlinks set because a required env var is missing: `VITE_GRAASP_REDIRECTION_HOST`. 
Added a build time requirement for it and added it to all deployment envs.
close #809

fix: add missing env var for go links

---

src/config/i18n.ts
src/ui/PlatformSwitch/PlatformSwitch.stories.tsx
src/ui/PlatformSwitch/PlatformSwitch.tsx

While trying to fix the tests in #803 I had some weird test failures caused by what looked liked re-renders.
When investigting what could possibly cause these re-renders (when clicking to change the item type in the add new item modal), I saw that the translation file for the `messages` namespace was being loaded. 
Coupled with this insight I set on looking why loading new translations might cause a full page reload ... and I found https://stackoverflow.com/questions/68455594/page-flickers-when-lazy-loading-translations-with-i18next-http-backend
And indeed, adding the `{react: { useSuspense: false } }` setting in the i18n config solved the issue. 
I also changed the PlatformSwitch buttons to be TSR links instead of dumb anchor tags, which removes the flickering when navigating between …

fix: flicker caused by suspense when loading translations

---

cypress/e2e/builder/map/map.cy.ts
src/config/selectors.ts
src/modules/builder/map/components/CountryForm/CountryForm.tsx
src/modules/builder/map/components/Map.tsx
src/modules/builder/map/components/map/CurrentMarkerPopupContent.tsx
src/routes/builder/_layout/index.tsx

close #774 
Country selection was always active because it only relied on the absence of currentGeolocation for the user. 
I added a state variable that disables the country selection after a successful first selection.
I also re-enabled the test.

fix: country selection

---

src/AuthContext.tsx
src/main.tsx

In this PR I add the sentry release health feature by setting the current user when we know they are authenticated. This will help to track release adoption and health.
I only pass `id` and `name` as info to share the least possible.

fix: add sentry session for Release Health reporting

---

src/locales/en/common.json
src/routeTree.gen.ts
src/ui/UserSwitch/UserSwitchWrapper.stories.tsx
src/ui/UserSwitch/UserSwitchWrapper.tsx

I added `settings` in the user drop down. 
The `UserSwitchWrapper` needs a lot of refactor, but I did a little bit while at it:
- factor out some translations
- show smaller icons
Remaining changes I can envision for further PRs:
- change the `redirect` mechanism to use links
- refactor the component to get actions as `children` instead as props. That would allow to factor out the `hooks.signOut`
- At some point get rid of the "wrapper"

feat: add settings in member drop down

---

.github/workflows/test.yml
cypress/e2e/account/homePage.cy.ts
cypress/e2e/home/home.cy.ts
src/modules/account/home/recentItems/RecentItems.tsx
src/modules/builder/components/pages/BuilderPageLayout.tsx
src/routes/_memberOnly/home.tsx
src/ui/Main/Main.tsx

- Reduced the number of shown recent items
- display as is the accessible items (no map)
- add same tests as builder "home"
Titles do not really make sense currently, because it is set lower in the components, and is used by pages like "published" or "trash". Should we decrease all titles, or pass down the titles are components?
https://github.com/user-attachments/assets/c022961b-6e57-4fe6-b985-ccfa87e44eb5
close #833

feat: add accessible items on home page

---

cypress/e2e/builder/item/authorization/membershipRequest/membershipRequest.cy.ts
cypress/support/server.ts
src/routes/builder/items/$itemId.tsx
src/routes/player/$rootId/$itemId/index.tsx

This PR solves the problem where before a hidden item could show the membership request feature. It was because the requesting was based on the fact that an item was not found + had no item login schema. It did not make the difference between `ITEM_NOT_FOUND` and item schema type `null`. 
So the fix is based on the returned value of `itemLoginSchemaType` that could return an error. If it's the case the item might not exist or be hidden. In those case we do not show the membership request button.

fix: do not allow membership request for hidden items

---

src/locales/ar/builder.json
src/locales/de/builder.json
src/locales/en/builder.json
src/locales/en/common.json
src/locales/es/builder.json
src/locales/fr/builder.json
src/locales/it/builder.json
src/modules/builder/components/layout/Navigation.tsx
src/modules/builder/components/main/MainMenu.tsx
src/ui/Navigation/Navigation.stories.tsx
src/ui/Navigation/Navigation.tsx
src/ui/UserSwitch/UserSwitchWrapper.tsx

- Move "Tutorials" to "Need help?" in user drop down
- Remove root from breadcrumbs 
- Add "Return to Home" instead of "tutorials" at the bottom of the drawer
close #838

feat: move tutorials in user drop down, add return home button

---

src/components/ui/HeaderRightContent.tsx
src/locales/en/common.json
src/ui/UserPopupMenu.stories.tsx
src/ui/UserPopupMenu.tsx

In this PR:
Change text in user menu popup from "Profile" to "Home".
In builder:
In home (notice that since we are in the /home route, the item is selected):
close #914

fix: change profile to home in user menu popup

---

src/config/queryClient.ts
src/query/queryClient.ts
src/query/test/constants.ts
src/query/test/utils.tsx
src/query/test/wsUtils.tsx
src/query/types.ts

No ws client was defined for prod. I simplified the code as well to remove the `WS_HOST` prop.

fix: simplify ws config in query client, define a ws client for prod

---

cypress/e2e/builder/item/view/viewFolder.cy.ts
src/locales/en/builder.json
src/locales/fr/builder.json
src/modules/builder/components/item/ItemMain.tsx
src/modules/builder/components/item/header/ItemHeader.tsx
src/routes/builder/items/$itemId.tsx
src/routes/builder/items/$itemId/index.tsx
src/ui/Navigation/Navigation.tsx

- Move "Return to Home" at the top of the drawer
- Remove `showNavigation` that was never used `false`
- Do not show breadcrumb navigation in root of the hierarchy

refactor: move home button to top, remove unused showNavigation prop

---

src/modules/builder/components/item/ItemContent.tsx
src/ui/items/AppItem.tsx
src/ui/items/appItemHooks.ts
src/ui/items/withCaption.tsx

In this PR I fix an issue with app resizing.
The current situation is that apps that want to be perfectly fit (using the autoresize hook) will send their height and it will be applied to the `height="xxx"` prop of the iframe. 
The apps that do not send this info will not have a height set, sot hey will be very small.
We want:
- apps using auto-resize should have their specified height used
- apps **not** using auto-resize should have a large height (around the full-viewport)
- apps using the resizable wrapper should be able to be resized by the component
The issue previously was that if we specified a height in the styling class, then the hook-provided height applied on the element directly would be override it, because it has lower specificity.
The fix is to change where we put the …

fix: app resizing issue

---

src/config/notifier.ts
src/locales/fr/account.json
src/modules/account/settings/ExportMemberData.tsx
src/query/member/mutations.test.ts
src/query/member/mutations.ts
src/query/member/routines.ts

I removed the `exportData` mutation to use the generated one. I removed the use of the notifier, showing alert instead.

feat: use export member data generation, remove notification

---

cypress/support/server.ts
src/config/notifier.ts
src/modules/account/settings/password/CreatePassword.tsx
src/modules/account/settings/password/EditPassword.tsx
src/modules/auth/components/signIn/MagicLinkLoginForm.tsx
src/modules/auth/validation.ts
src/query/member/api.ts
src/query/member/mutations.test.ts
src/query/member/mutations.ts
src/query/member/routines.ts

I replace the `updatePassword` and `createPassword` endpoints to avoid using `notifier`.
ref #819

fix: use update password generation to fix translation

---

src/routeTree.gen.ts
src/routes/builder/index.tsx

Prevent `/builder` to lead to a non found route. Instead it leads to `/home`, our new home page.

fix: redirect builder to home

---

src/config/i18n.ts

In this PR I update the language detection priority so the language query string is considered before the local storage or the navigator.
This allows urls from the documentation to specify for example: `http://graasp.org/auth/register?lang=fr` and the register page will be in french.

fix: use language query string when present

---

.github/workflows/test.yml
package.json
pnpm-lock.yaml
src/modules/builder/components/item/sharing/shareButton/CreateItemMembershipForm.tsx

In this PR I remove the `validator` dependency.
We have the `isEmail` function already implemented in `@graasp/sdk`.
We do not need the extra package.

fix(deps): remove validator dep

---

src/locales/en/builder.json
src/locales/fr/builder.json
src/modules/home/MaintenanceAnnouncement.tsx
src/modules/player/item/MainScreen.tsx
src/routes/_landing/index.tsx
src/routes/_memberOnly/_homeLayout/home.tsx

I have updated the format of the date to remove the seconds. I don't think we are time critial to the point where we need seconds in the announcement. You can compare the previous format and the proposed format in the image below:

fix: add the contact information to the maintenance banner

---

cypress/e2e/player/hidden.cy.ts
src/config/notifier.ts
src/locales/ar/builder.json
src/locales/ar/messages.json
src/locales/de/builder.json
src/locales/de/messages.json
src/locales/en/builder.json
src/locales/en/messages.json
src/locales/es/builder.json
src/locales/es/messages.json
src/locales/fr/builder.json
src/locales/fr/messages.json
src/locales/it/builder.json
src/locales/it/messages.json
src/modules/builder/components/file/FileUploader.tsx
src/modules/builder/components/hooks/uploadWithProgress.ts
src/modules/builder/components/item/form/file/UploadFileModalContent.tsx
src/modules/builder/components/main/ImportH5P.tsx
src/modules/builder/components/main/list/ItemsTable.tsx
src/modules/builder/components/thumbnails/ThumbnailUploader.hook.tsx
src/ui/upload/FileDropper/FileDropper.stories.tsx
src/ui/upload/FileDropper/FileDropper.tsx

The frontend shows the file-upload errors correctly:
- drop zone (modal, empty folder): shows the error in the dropzone
- drop in between rows: shows a notification
I guess it would be easier to have the same mechanism however we upload the file. So to move to notifications/progress dialog.
https://github.com/user-attachments/assets/27bc025d-99cc-4c72-a62f-46cf83124957
https://github.com/user-attachments/assets/cc2c5d48-d8df-4a8a-b8c4-df9dfaa3c32d
https://github.com/user-attachments/assets/945c1b95-00ef-4490-bdbb-732f62320af8

fix: show error notifications on file upload

---

package.json
pnpm-lock.yaml
src/query/utils/util.ts

We have still some failures (flacky) with the vitest query suite. 
In this PR I upgrade `happy-dom` to try to make them disappear. It is possible that react 19 which we are using is more strict about DOM apis... let's see.
It that does not resolve it, we could switch to `jsdom` which is more feature complete be also a bit heavier.
Otherwise an option is to focus our work on moving more code to the generation and minimise and remove the query test suite.

fix: upgrade happy-dom to fix issues with query tests

---

cypress/e2e/builder/item/create/createFolder.cy.ts
cypress/e2e/builder/item/edit/editFolder.cy.ts
src/config/constants.ts
src/locales/en/messages.json
src/modules/builder/components/item/edit/EditModal.tsx
src/modules/builder/components/item/form/description/DescriptionAndPlacementForm.tsx
src/modules/builder/components/item/form/description/DescriptionForm.tsx
src/modules/builder/components/item/form/folder/FolderCreateForm.tsx
src/modules/builder/components/item/form/folder/FolderEditForm.tsx

In this PR I fix #1049 
Currently users can enter a description that is longer than the allowed length (5000 chars in the backend).
I fix this problem by:
- adding an error message when the description is too long
- disabling the submit button so users can't save a description that is too long
- make `create` and `edit` folder forms validate the inputs `onChange` to increase the feedback to the user (previously they would only validate `onSubmit`
While working on this I noticed that the validation mode for the create and edit modals for the folder was set to `onSubmit`. I do not know if there was a reason behind it. @pyphilia do you know ?
Also I changed the `DescriptionForm` component to use `<Controller />` from react-hook-form to make validation more straight forward.
I also changed …

fix: notify users when the description is too long

---

cypress/e2e/builder/item/copy/copy.cy.ts
src/locales/en/builder.json
src/locales/fr/builder.json
src/modules/builder/components/item/copy/CopyWarningModal.tsx
src/modules/builder/components/item/header/Actions.tsx
src/routes/auth.tsx
src/routes/builder/items/$itemId.tsx
src/routes/builder/items/$itemId/index.tsx
src/ui/buttons/CopyButton/CopyButton.tsx

Add copy item menu in item page. 
Otherwise it is not possible to copy the root (if you come from library for example)

feat: add copy in item page menu

---

src/components/page/Editor.tsx
src/components/page/StatusToolbar.tsx
src/components/page/useYjs.ts
src/locales/en/pageEditor.json

In case the server is throwing an error and closing the connection, the collaboration plugin will retry infinitely to connect (it's the server that failed).
If the error repeats, we can end up in a infinite loop where the websocket gets connected and disconnected repeatedly.
The current timeout implemetation is based on how many times disconnection happens in a short period of time. If we get disconnected 5 times in less than 2 seconds, the interface will show an error and hide the document.
I personally it is a bit shaky as a solution, but since we don't really have access to the websocket provider implementation, I don't really control the retrial mechanism. For now it is okay, let's see how it plays in the sandbox. If later we need more control on the awareness (for example) it will …

fix(page): timeout connection attempts if disconnections are repeated

---

pnpm-lock.yaml
src/query/hooks/useDebounce.ts
src/query/item/create/mutations.test.ts
src/query/item/h5p/mutations.test.ts
src/query/item/import-zip/mutations.test.ts
src/query/item/mutations.test.ts
src/query/item/reorder/mutations.test.ts
src/query/item/thumbnail/mutations.test.ts
src/query/member/mutations.test.ts
src/query/mutations/invitation.test.ts
src/query/mutations/itemExport.test.ts
src/query/mutations/itemGeolocation.test.ts
src/query/mutations/itemLogin.test.ts
src/query/mutations/itemPublish.test.ts
src/query/mutations/itemValidation.test.ts
src/query/mutations/itemVisibility.test.ts
src/query/mutations/mention.test.ts
src/query/test/utils.tsx

In this PR I try to address the recurrent issue of failing vitest tests. 
The issue seemed to be linked to a dangling `setTimeout` that is called after test teardown. 
This can happen when using `waitForMutation` in case the test terminates before the timeout. 
I simplified the tests by moving all calls from `mockedMutation.mutate()` to `mockedMutation.mutateAsync()` also removing the unnecessary `act()`.
On mutations that throw because of errors (UNAUTHORIZED, file too large etc...) I added an expect toThrow.
Hopefully this fixes the flackyness of the vitest suite.

fix: remove `waitForMutation` and use `await expect(...).rejects.toThrow()` on throwing mutations
